# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA', '.' ]
# push docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA']
# Create the new instance template
- name: 'gcr.io/cloud-builders/gcloud'
  #id: create-instance-template
  args:
    - 'compute'
    - 'instances'
    - 'create-with-container'
    - 'calculator'
    - '--custom-cpu=1'
    - '--custom-memory=2GB'
    - '--boot-disk-size=20GB'
    - '--region=asia-south1'
    - '--tags=allow-hc-and-proxy,allow-ssh,http-server'
    - '--container-image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA'
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA'