# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA', '.' ]
# push docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA']
# Create the new instance template
- name: 'gcr.io/cloud-builders/gcloud'
  #id: create-instance-template
  args:
    - 'compute'
    - 'instances'
    - 'create-with-container'
    - 'calculator'
    - '--scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append'
    - '--create-disk=auto-delete=yes,boot=yes,device-name=calculator,image=projects/debian-cloud/global/images/debian-11-bullseye-v20230306,mode=rw,size=10,type=projects/neural-cairn-382610/zones/us-west4-b/diskTypes/pd-balanced'
    - '--boot-disk-size=20GB'
    - '--zone=asia-south1-c'
    - '--tags=allow-hc-and-proxy,allow-ssh,http-server'
    - '--container-image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA'
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA'