# build docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA', '.' ]
# push docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA']
# Create the new instance template
- name: 'gcr.io/cloud-builders/gcloud'
  #id: create-instance-template
  args:
    - 'compute'
    - 'ssh'
    - 'cloudbuild@ssh-calculator'
    - '--zone=asia-south1-c'
    - '--tunnel-through-iap'
    - '--command="sudo docker ps"'
#inside ssh
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['run', '-p', '80:80', '--name', 'calculator', '-d', 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA', ]
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/docker/github.com/dhruvrkashyap/javascript:$COMMIT_SHA'